### PR TITLE
Extract Container from index.js to pages' components

### LINKED ISSUE #78: Remove Container from index.js
it's throwing console warnings
## Expected Behavior

individual pages' components can be wrapped in a container
## Current Behavior

everything is wrapped in a container eliciting warnings

screenshot at 2019-02-11 09 19 48

### PR DESCRIPTION
**Pull request by mattwr18**
#### Issue addressed

fixes #78

### CODE REVIEW

**Comment by joaopapereira** [comment]
@mattwr18 can you please revisit this PR, does it still make sense and if so can you please correct the conflicts?

**Comment by joaopapereira** [comment]
@mattwr18 please review the conflicts in this PR

**Comment by mattwr18** [comment]
I saw your comment, sorry I didn't respond... the changes are minor and probably best to wait till after the other PayPal changes are merged in... then I can create a fresh branch off of develop and cherry-pick the commit from this `PR` and put in another... what do you think?

**Comment by mattwr18** [comment]
anyways, I've merged in develop, if you don't care about the commit history... otherwise, I can do what I said above

**Comment by mattwr18** [comment]
anything holding this up @joaopapereira?

**Review by joaopapereira — APPROVED** [review]
Looks good
Going to merge

**Pull request merged**
