### PR TITLE
Add new project button

### PR DESCRIPTION
**Pull request by sudodaksh**
#### Issue addressed
Add new project button

#### Screenshots (if appropriate):
image

### CODE REVIEW

**Review by joaopapereira — CHANGES_REQUESTED** [review]
Currently we are using semanticui to do all the CSS part. 
Aparently semantic UI also includes fontawesome: https://semantic-ui.com/elements/icon.html

Do you think we can use the semantic UI instead of having to import font awesome?

**Comment by sudodaksh** [comment]
@joaopapereira addressed your concerns in the last commit!

**Comment by mattwr18** [comment]
great refactoring to use semantic ui icons @DakshMiglani! could you please remove `@fortawesome/fontawesome-svg-core` from the package.json?

**Comment by sudodaksh** [comment]
@mattwr18 done.

**Review by joaopapereira — APPROVED** [review]
Looks good, going to merge

**Pull request merged**
