### PR TITLE
Refactor Userlist use hooks

### LINKED ISSUE #32: Refactor some components to use react hooks.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by aonomike**
Refactors the UsersList component to use react hooks 
#### Issue addressed

fixes #32

### CODE REVIEW

**Comment by mattwr18** [comment]
great job @aonomike, could you please merge in the develop branch, work through the merge conflicts and push it back up so it can run the build?

**Comment by joaopapereira** [comment]
@aonomike can you please resolve these conflicts?

**Comment by mattwr18** [comment]
@joaopapereira we talked about this `PR` in the react mob today and we thought it might be best to table it at least until after the MVP is delivered because it involves refactoring tests, and you voiced your concern of us using React Hooks at this stage. 

Maybe we can talk better in tomorrow's meeting?

**Comment by mattwr18** [comment]
@aonomike thanks for getting this going, I am really looking forward to using react hooks, but we can't prioritize this refactor at the moment since the priority is to get this in production and they are still so new. Also, we have chosen to use enzyme in our tests and they don't support testing them at the moment.
react-testing-library does, but cannot be used in parallel.

Hope you understand, we can always discuss reopening this in the future

**Pull request closed without merging**
