### PR TITLE
249 Refactor ProjectForm to make use of two columns of fields

### LINKED ISSUE #249: Refactor ProjectForm to make use of two columns of fields
## Expected Behavior

There should be two columns of fields(input, selects), so that there is more "above the fold" for the user to see, and not need to scroll down so much.
Also, we now have a reusable `FormButton` component that could be used to keep the buttons the same relative size/color
Screenshot at 2019-05-21 20:26:15

## Current Behavior

At the moment there is just one column so the fields are too wide and a user must scroll down to see the buttons they can click on to create/edit a project.
Also, the `Create Project` button is directly beneath the other buttons and is more the color of our cancel buttons.
Screenshot at 2019-05-21 20:25:26
Screenshot at 2019-05-21 20:25:37

## Possible Solution

We can make use of `Semantic UI`s `Grid` to create two columns each with their own fields
https://react.semantic-ui.com/collections/grid/
## Steps to Reproduce (for bugs)

1. go to `/events/new`
2. check out the form

### PR DESCRIPTION
**Pull request by 47analogy**
#### Issue addressed

fixes #249

### CODE REVIEW

**Review by aonomike — DISMISSED** [review]
Looks good to me @47analogy @mattwr18 @joaopapereira , I am not sure we should add tests to check the presence of the rows and column? I dont see that necessary though. Thanks for working on this @47analogy

**Comment by aonomike** [comment]
Hi @47analogy this PR looks good to me, but seems you may have to remove the WIP tag before I approve. Is there something more you wanna add to this PR?

**Comment by aonomike** [comment]
Screen Shot 2019-06-27 at 9 56 01 PM

**Comment by 47analogy** [comment]
@aonomike  no more additions

**Review by aonomike — APPROVED** [review]
Looks good to me. Thanks @47analogy

**Comment by mattwr18** [comment]
so, this is ready to merge @aonomike ??

**Pull request merged**
