### PR TITLE
#52 add stripe support

### PR DESCRIPTION
**Pull request by sudodaksh**
Adds stripe checkout support.

Dependencies added:

- react-stripe-checkout

What's left:

- Add Stripe API Key
- Once checkout is complete, make an API request website-one backend.

What's done:

- Made a stripe checkout component with props such as: amount, api-key, name.

Screenshots:

### CODE REVIEW

**Review by joaopapereira — CHANGES_REQUESTED** [review]
Can you please rebase your PR so that I can understand the changes that you did?
Thanks

**Comment by sudodaksh** [comment]
@joaopapereira rebase to which commit?

**Comment by joaopapereira** [comment]
@DakshMiglani did you meant to create a PR against: AgileVentures:39-add-paypal-payment-support ?
Or is this to add to development branch?

**Comment by sudodaksh** [comment]
@joaopapereira I meant to create it against 39-add-paypal-payment-support.

**Comment by joaopapereira** [comment]
@DakshMiglani what is the reasoning behind it?
Does it have functionality that you need that is currently not in `develop`?

**Comment by sudodaksh** [comment]
@joaopapereira because when I wrote the code, matt's pr wasn't merged in the develop branch and the code is dependent on it.

**Comment by joaopapereira** [comment]
Ok I think that I merged the 39 branch, @DakshMiglani do you mind pointing this PR to `develop` branch?

**Comment by sudodaksh** [comment]
@joaopapereira done, but I might have to adjust the code as per matt's updates. I'll ping you once I'm done!

**Comment by joaopapereira** [comment]
Ok

**Comment by sudodaksh** [comment]
@mattwr18 @joaopapereira I think it's done, atleast from my side. waiting on others for the changes!

**Comment by mattwr18** [comment]
yeah, @DakshMiglani as we discussed, I think we can wait till the last of the changes to the PayPal stuff gets merged in, create a new branch, cherry-pick the relevant changes, and then put in a `PR`, which has the history of just the relevant changes... and also we need to add tests no? It's looking good though thanks!! :smile:

**Comment by sudodaksh** [comment]
yes! we'll do all of that in due time.

**Pull request closed without merging**
