### PR TITLE
Create now.json

### LINKED ISSUE #56: create a zeit.co av account
create a zeit.co av account

### PR DESCRIPTION
**Pull request by mattwr18**
set up automated deploys
#### Issue addressed

fixes #56

### CODE REVIEW

**Comment by mattwr18** [comment]
looks like we need to have a root level index file for these to work https://zeit.co/docs/v2/routing/directory-listing

**Comment by joaopapereira** [comment]
@mattwr18 did you fix the routing issue?

**Comment by mattwr18** [comment]
no, not sure what we need to have in this root level index file... @Kachulio1 any ideas?

**Review by joaopapereira — APPROVED** [review]
Looks like it is deploying

**Pull request merged**
