### PR TITLE
 add common button

### PR DESCRIPTION
**Pull request by Kachulio1**
#### Issue addressed

fixes #

### CODE REVIEW

**Review by dkuku — COMMENTED** [review]
@kachulio1 You requested a review but I'm not really sure whats the purpose of this component and what the difference between this component and the buttons from the ui framework we use? Even the name is the same which might be confusing when it's using different props.
I think we need to decide on using one or the other to keep the layout consistient.
There is no description. Otherwise the code looks good to me.

**Comment by Kachulio1** [comment]
@dkuku yeah I thought it would be a good idea to use as little semantic UI as possible because when the new designs come, they will not be based on semantic UI, and also I foresee the pain of trying to add something or tweak an element in a certain way it'll be difficult like what we experienced with react-create-app e.g I can see we have `!important` in the User.css because we want to override some CSS property for semantic.

**Comment by Kachulio1** [comment]
I believe it's about time we start writing our own CSS. 
What do you think?

**Comment by Kachulio1** [comment]
So that AgileVentures can have that good look and feel and most importantly originality.

**Comment by dkuku** [comment]
I don't know - for me there is no clear roadmap for this project. I prefer
to work on something thats more mature.

**Comment by mattwr18** [comment]
@dkuku I think we are the ones who are creating the roadmap. I think that sometimes it can be easier to have a clear direction of what to build with clear design choices and wireframes, etc.. but I enjoy being part of the process. 

Do you feel like your opinions are being heard?

**Comment by mattwr18** [comment]
@Joseph I know that @javpet is a fan of that approach, for me it's more difficult to do it that way, I like having the ability to just use `<Button>`, which has props that I can use.

Also, I think the idea of the route @dkuku was taking with using semantic ui as a base, but building a custom theme would largely give us the ability to customize it pretty much however we want, but maybe I misunderstood what the purpose of his PR was. 

Is this how you understand it @dkuku?

**Comment by dkuku** [comment]
@mattwr18 @Kachulio1 kachulio1 I don't mean only the UI, but the project as a whole.
In the previous version I started fixing the calendar but I've heard that
it might not get used at all. Then I moved to the semantic ui stuff because
of the mess with css overrides and now I head that it might get replaced
soon, so I really don't want to waste my time on something with no clear
vision. I need some projects in my portfolio that are running in production
and that I can show off to my potential employer when looking for job and
here I can only say that I've done this and that but it was scrapped and
you can see the commit -  which no one will look at.

-- 
Sincerely
Daniel Kukuła

**Comment by mattwr18** [comment]
hey @dkuku I'm sorry if you feel like you are wasting time! That is not what anyone wants!! I can assure you that your contributions are greatly appreciated by all!! I remember that in the React Mob, we talked for a good half an hour or more on what CSS framework to use, and agreed that we didn't want to stay with bootstrap, there was no clear 2nd, but we decided the four of us together to switch to Semantic UI. At the time I don't think anyone realized that it had a real shot at going into production. 

As far as the calendar, I don't think anything has been decided except that we would like to get it built and into production sooner rather than later, which is partly why we decided to use the BigCalendar, instead of build one from scratch. I think the improvements you made to the Events page have a great chance of getting used!  

I think it would be a shame if you didn't want to continue helping realize this project, as I believe we are the closest we've ever been to having an organized workflow and everyone pulling more or less in the same direction, but I respect your decision if you feel like you'd rather do something else.

**Comment by dkuku** [comment]
@mattwr18 I'm just saying that I need a vision of the project. I see that @joaopapereira already wrote something in slack - thanks. 
For me when I have an ui framework available I use it as much as possible, @Kachulio1 thinks it's a good idea to use as little semantic UI as possible - how should we review each other code in a project with no clear goals? And I'm not saying that because I made the semantic build - I don't need to use it, i learned how to do this and I'm happy about that. 
I just want to know the plans for this project, what we want to use and what we don't want to use - that's why I said I prefer to work on more mature projects because this one is not clear at all to me.

**Comment by Kachulio1** [comment]
a

**Pull request closed without merging**
